#!/bin/bash -e

# Usage: /sbin/backup-mail
backupPath="/data/backup"

source /etc/container_environment.sh

# delete backups that are over $MMC_MAIL_BACKUP_MAX_DAYS days
find $backupPath -type f -mtime +$MMC_MAIL_BACKUP_MAX_DAYS -exec rm {} \;

# Date format for the dump file name
dateFileFormat="+%F-%T"
backupFilePath="$backupPath/$(date "$dateFileFormat")-mail.tar.gz"

tar -czf $backupFilePath -C / var/mail
