#!/bin/bash -e

# Usage: /sbin/slapd-backup dbnum filename
pathBackup="/data/backup"

# Date format for the dump file name
dateFileFormat="+%F-%T"
pathBackupFile="$pathBackup/$(date "$dateFileFormat")-mail.tar.gz"

tar -czf $pathBackupFile -C / var/mail
