#!/bin/bash -e

# Usage :
# /osixia/service/dovecot/assets/config/enable-config [config1] [config2] ...

for i in $@
do

  if [ -f /osixia/service/dovecot/assets/config/config-available/$i/enable.sh ]; then
    /osixia/service/dovecot/assets/config/config-available/$i/enable.sh
  else
    echo "enable-config: dovecot config $i not found."
    exit 1
  fi

done
