#!/bin/bash -ex

# delete preexisting autogenerated files
[ -f /etc/opendkim/KeyTable ] || rm -f /etc/opendkim/KeyTable
[ -f /etc/opendkim/SigningTable ] || rm -f /etc/opendkim/SigningTable

touch /etc/opendkim/KeyTable
touch /etc/opendkim/SigningTable

# list mail domains

LDAP_AUTH=""
if [ -n "${LDAP_BIND_DN}" ]; then
  LDAP_AUTH="-D ${LDAP_BIND_DN}"
fi
if [ -n "${LDAP_BIND_PW}" ]; then
  LDAP_AUTH="$LDAP_AUTH -w ${LDAP_BIND_PW}"
fi

# better way ?
HOST_FILE="ldap-hosts"
touch $HOST_FILE

ldapsearch -x -H ${LDAP_URL} -b ${LDAP_BASE_DN} "(&(objectClass=mailDomain)(virtualdomain=*))" ${LDAP_AUTH} | grep "virtualdomain:" > ${HOST_FILE} || true
sed -i "s/virtualdomain: //g" $HOST_FILE

for domain in $(cat $HOST_FILE);
do
  # the domain private key don't exists -> generate one
  if [ ! -f "/etc/opendkim/keys/$domain.key" ]; then
    opendkim-genkey --domain=$domain --append-domain --selector=$OPENDKIM_SELECTOR --directory /etc/opendkim/keys
  fi

  echo "*@$domain:$domain:/etc/opendkim/keys/$domain.key" >> /etc/opendkim/KeyTable
  echo "*@$domain $OPENDKIM_SELECTOR._domainkey.$domain." >> /etc/opendkim/SigningTable

done
